name: Publish to PyPI

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  # Setup build separate from publish for added security
  # See https://github.com/pypa/gh-action-pypi-publish/issues/217#issuecomment-1965727093
  build:
    runs-on: ubuntu-latest
    # Environment is encouraged for increased security
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          # This fetch element is only important if you are use SCM based
          # versioning (that looks at git tags to gather the version).
          # setuptools-scm needs tags to form a valid version number
          fetch-tags: true

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          # You can modify what version of Python you want to use for your release
          python-version: "3.11"

      - name: Install hatch
        run: |
            python -m pip install --upgrade pip
            python -m pip install hatch

      - name: Build package using Hatch
        run: |
            hatch build

            echo ""
            echo "Generated files:"
            ls -lh dist/
      # Store an artifact of the build to use in the publish step below
      - name: Store the distribution packages
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v4
        with:
          name: python-package-distributions
          path: dist/
          if-no-files-found: error
  publish:
    name: >-
      Publish Python üêç distribution üì¶ to PyPI
    # Only publish to PyPI with a release trigger in your repository.
    if: github.repository_owner == 'yuvipanda' && github.event_name == 'release'
    needs:
      - build
    runs-on: ubuntu-latest
    # Environment required here for trusted publisher
    environment:
      name: pypi
      # Modify the url to be the name of your package
      url: https://pypi.org/p/jupyterbook_pub
    permissions:
      id-token: write  # this permission is mandatory for PyPI publishing
    steps:
      - name: Download dists
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v4
        with:
          name: python-package-distributions
          path: dist/
          merge-multiple: true
      - name: Publish package to PyPI
        # Only publish to real PyPI on release. This action uses sigstore for additional security.
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e #v1.13.0
